apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium-rlease
  namespace: cilium-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: ">=1.15.0-0"
  interval: 1h0m0s
  releaseName: cilium-rlease
  targetNamespace: cilium-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
