apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium-system
resources:
- namespace.yaml
- helmrepository-cilium.yaml
- helmrelease-cilium.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=cilium-values.yaml
configurations:
- kustomizeconfig.yaml
