---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: keycloack-repo
  namespace: keycloack-system
spec:
  interval: 5m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts