apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloack
  namespace: keycloack-system
spec:
  interval: 10m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloack-repo
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: keycloack-values