apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway-crds
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway-api
      sourceRef:
        kind: HelmRepository
        name: gateway-api
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
