apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloack-system
resources:
- namespace.yaml
- helmrepository-keycloack.yaml
- helmrelease-keycloack.yaml
configMapGenerator:
  - name: keycloack-values
    files:
      - values.yaml=keycloack-values.yaml
configurations:
- kustomizeconfig.yaml
