apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiengine-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - ai-engine.cloud
    secretName: aiengine-tls
  rules:
  - host: ai-engine.cloud
    http:
      paths:
      - pathType: Prefix
        path: /keycloak/(.*)
        backend:
          service:
            name: keycloack-keycloak.keycloack-system.svc.cluster.local
            port:
              number: 80
